huffman: heap/heap.c huffman/huffman.c frequency/frequency.c codes/codes.c compress/compress.c main.c
	gcc -o main heap/heap.c huffman/huffman.c frequency/frequency.c codes/codes.c compress/compress.c main.c

clean:
	rm main