huffman: util/util.c heap/heap.c huffman/huffman.c frequency/frequency.c codes/codes.c decompress/decompress.c compress/compress.c main.c
	gcc -o main util/util.c heap/heap.c huffman/huffman.c frequency/frequency.c codes/codes.c decompress/decompress.c compress/compress.c main.c

clean:
	rm main